### ISSUE TITLE
Feature request: Contains

### ISSUE THREAD

**Issue by JamesMcIntosh** [tonio-ramirez/optional.dart#10]
To save HEAPS of code unwrapping or mapping it would be great to have a contains. Currently I have to:
```
T t = ...;
Optional<T> o = Optional.of(t);
bool contains1 = o.map((v)=>v == t).orElse(false);
bool contains2 = o.isPresent ? o.value == t : false;
```

Suggested signature and implementation
```
Signature:
  bool contains(T val);
Absent:
  bool contains(T val) => false;
Present:
  bool contains(T val) => _value == val;
```

**Comment by tonio-ramirez** [comment]
`Optional` currently implements the `==` operator, so your code could look like:

```dart
T t = ...;
Optional<T> o = Optional.of(t);
bool contains1 = o == Optional.of(t);
bool contains2 = o.orElse(null) == t;
```

Which, admittedly, does contain an "extra" wrapping which would be unnecessary with your `contains()` method proposal, but is not excessively verbose. `o == Optional.of(t)` and `o.orElse(null) == t` are both 17 non-whitespace characters, while `o.contains(t)` is 13 non-whitespace characters.  I hesitate to introduce a new method to save 4 characters.
Consider that if all you're going to do is compare the possible value with a reference value, the `contains()` method would save you 4 characters, but if you'll use the possible value for other operations, you should already be doing something like:

```dart
T t = ...;
Optional<T> o = Optional.of(t);
if(o.isPresent) {
  T val = o.value;
  // use val
}
// or, optionally
o.ifPresent(val => /* use val */);
```

**Comment by tonio-ramirez** [comment]
Sorry, hit "Close and comment" when I meant to hit "Preview" (yah, they're not even close... dunno what happened).

**Comment by JamesMcIntosh** [comment]
Looks like we are talking about different things, I mean "saving" more in terms of code complexity rather than the number of characters of the code.

I guess the best way I can explain why I think this is a must have feature is that if you get a person to read any of the examples you or I have given and to explain what they do, is the answer obvious? In all cases it is "no" as you have to work through the code.

`o == Optional.of(t)` is the easiest of the examples to reason about but having to wrap, `o.contains(t)` couldn't be any more elegant.

As a side note, I see that you have used Java's implementation as a starting point, I would much more recommend having a look at Scala's Option as it is much easier to use.
https://www.scala-lang.org/api/current/scala/Option.html

**Comment by tonio-ramirez** [comment]
Although I was tangentially aware of Scala's Option, I am not fluent with the language.  Java is my primary language, so I picked that as a starting point.

I do see your point, though.  I'll make the change.  I'll include `toSet` and `toList`, which I'd been considering for a while.

**Comment by JamesMcIntosh** [comment]
Awesome!
I'm also very excited about the addition of `toList` as I've had to do that a few times already on my current project. Thanks very much!
