### ISSUE TITLE
Optional extension method

### ISSUE THREAD

**Issue by JamesMcIntosh** [tonio-ramirez/optional.dart#11]
Hi @tonio-ramirez 

I have a proposal to include an extension method for creating Optionals which avoids wrapping every instance you create in the factory constructor `Optional.of()`.

The syntax extension makes it possible to write this following:
```
Optional<MyObject> oMo = Optional.of(mo);
```
like this instead:
```
Optional<MyObject> oMo = mo.toOptional;
```

It is also has the benefit that it becomes about 10 times quicker to construct the Optional as you get code completion from the IDE!

```
import 'package:optional/optional.dart';

extension OptionalExtension<T> on T {

  Optional<T> get toOptional => Optional.ofNullable(this);

}
```

The only downside when making this change is it increases the SDK dependency for Dart from 2.0.0 to 2.6.0 to get the new language feature.

My personal view on the SDK dependency is that the current state of the library is extremely "stable" such that anyone on who requires a <2.6.0 SDK dependency is most likely going to be require any bug fix releases.

You could probably get away with a major version bump to v4 to accompany the change if you wanted to keep the door open for a legacy v3 branch for any bug fixes which may happen where you wanted to maintain 2.0.0 compatibility.

**Comment by tonio-ramirez** [comment]
I like it!

Should be published in a couple of minutes.
