### ISSUE TITLE
Would like to have a way to get an async value if not present without having to use casts.

### ISSUE THREAD

**Issue by JSANL** [tonio-ramirez/optional.dart#12]
I want to load a chat if one is present or else create one asynchronously.   
Lets imagine i have a chat app. 

What I would like to write is something like this:

```dart
  Future<ChatView> loadOrCreateChat(String id) async {
    final maybeChat = await repository.loadChat(id);
    final chat = await maybeChat.orElseGetAsync(() => _createChat(id));
    return chatViewFactory.createView(chat);
  }
```

What I have to write is:

```dart
  Future<ChatView> loadOrCreateChat(String id) async {
    final maybeChat = await repository.loadChat(id);
    final casted = maybeChat.cast<FutureOr<Chat>>();
    final chat = await casted.orElseGet(() => _createChat(id));
    return chatViewFactory.createView(chat);
  }
```

Basically I dont want to cast manually.

Here is a minimal example:

```dart
import 'dart:async';

import 'package:optional/optional.dart';
import 'package:test/test.dart';

void main() {
  ChatViewLoader bloc;
  ChatRepository repository;

  setUp(() {
    repository = ChatRepository();
    bloc = ChatViewLoader(repository, ChatViewFactory());
  });

  test('creates chat if chat from repo is empty', () async {
    repository.returnEmpty = true;

    final view = await bloc.loadOrCreateChat('id');

    expect(view.fromRepo, false);
  });
  test('does not create chat if chat from repo is non-empty', () async {
    repository.returnEmpty = false;

    final view = await bloc.loadOrCreateChat('id');

    expect(view.fromRepo, true);
  });
}

class ChatViewLoader {
  final ChatRepository repository;
  final ChatViewFactory chatViewFactory;

  ChatViewLoader(this.repository, this.chatViewFactory);

  Future<Chat> _createChat(String id) async {
    return Chat(false);
  }

  Future<ChatView> loadOrCreateChat(String id) async {
    final maybeChat = await repository.loadChat(id);
    final casted = maybeChat.cast<FutureOr<Chat>>();
    final chat = await casted.orElseGet(() => _createChat(id));
    return chatViewFactory.createView(chat);
  }
}

class ChatRepository {
  bool returnEmpty = true;
  Future<Optional<Chat>> loadChat(String id) async {
    return returnEmpty ? Optional.empty() : Optional.of(Chat(true));
  }
}

class Chat {
  final bool fromRepo;

  Chat(this.fromRepo);
}

class ChatView {
  final bool fromRepo;

  ChatView(this.fromRepo);
}

class ChatViewFactory {
  Future<ChatView> createView(Chat chat) async {
    return ChatView(chat.fromRepo);
  }
}
```

**Comment by tonio-ramirez** [comment]
Fixed in f840754b31d2c21fea0e76a0c3a79e36cc3c5376

**Comment by JSANL** [comment]
@tonio-ramirez Just saw that you already pushed it. Firstly thanks but secondly this is a breaking change and I don't really think that having `orElse` being a `FutureOr<T>` is the right thing. 

Now every code that is synchronous, lets say a method like this
```
int myMethod() {
 final someOptional = Optional.of(_someSychronousValueThatMayBeNull);
 return someOptional.orElse(3)
}
```
would need to be async unnecessarily:
```
Future<int> myMethod() {
 final someOptional = Optional.of(_someSychronousValueThatMayBeNull);
 return someOptional.orElse(3)
}
```

This means also all code which calls `myMethod` needs to be async which are many needless changes for codebases already using `Optional.orElse`.

So I think:
1. You should push an update undoing these changes (as a 4.3.0 version) [as you broke the semver contract](https://dart.dev/tools/pub/versioning#semantic-versions) (breaking changes should need a new major version, 5.x.x - correct me if I'm wrong of course).
2. I would advise to implement `orElse**Async` methods so that synchronous methods stay synchronous. e.g. `orElseGetAsync`.

**Comment by tonio-ramirez** [comment]
All my tests passed successfully, which is why I pushed the code and didn't change the major version.  It is not a breaking change.  Code written using the previous version will still work with this version, since `FutureOr<T>` is a super-type of `T`.  I did notice a dartanalyzer "error" from the code you provided, but it runs properly anyway.

I'll revert the `orElse()`, `orElseGet()`, and `orElseThrow()` methods to deal with `T` instead of `FutureOr<T>`, and add the `orElseGetAsync()` method as suggested, to avoid bogus dartanalyzer "error"s.  From what I gather reading https://github.com/dart-lang/language/issues/606, it seems like a good idea, anyway.  Thank you for pointing that out.

**Comment by tonio-ramirez** [comment]
Reverted `or*()` methods and added `orElseGetAsync()` in 472d146fd6fdf8cc24a3edb78cfbed3526dbbef7

**Comment by JSANL** [comment]
Ah okay, didn't know that this is "only" an analyzer error! This was also confusing for me as I saw your extensive testing :)  
I hope that the `orElseGetAsync` is the "cleaner" and most obvious solution.

Well thanks once again and sorry for causing the trouble.
