### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by crossle** [tonio-ramirez/optional.dart#14]

**Comment by nilsreichardt** [comment]
Here are some helpful resources:
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by tonio-ramirez** [comment]
Waiting on [`test_coverage` ](https://github.com/pulyaevskiy/test-coverage/issues/33)to support null safety.

**Comment by tonio-ramirez** [comment]
Removed `test_coverage` for now.  Null-safety support added in dbc01e951d63fe65218b797165fb3de5f65a46ce.

**Comment by crossle** [comment]
When publish the release version?

**Comment by tonio-ramirez** [comment]
I want to wait until `test_coverage` is updated to support null safety, and re-enable it, before publishing a release version.
