### ISSUE TITLE
Feature request: nullable orElse

### ISSUE THREAD

**Issue by JamesMcIntosh** [tonio-ramirez/optional.dart#15]
Hi @tonio-ramirez,

When using the library in a null safe context it becomes difficult to get a null out of the Optional without being verbose and using if statements or using `map<T?>(identity)`.

```
final Optional<String> data = Optional.of("data");
final String? value = data.orElse(null);
```
Fails analysis with
```
Error: The value 'null' can't be assigned to the parameter type 'String' because 'String' is not nullable.
```

Adding these to the library would make life easier
```
T? orElseNullable(T? other)
T? get orElseNull
```

Thanks again for the awesome library!
James

**Comment by tonio-ramirez** [comment]
Added in 883d2d768c76575ac03d5a5ea1b0505e88ce1376.  Should be available in pub soon.
