### ISSUE TITLE
OptionalExtension does not support null.toOptional

### ISSUE THREAD

**Issue by JamesMcIntosh** [tonio-ramirez/optional.dart#16]
Hi @tonio-ramirez,

Can you please revert the change made to `OptionalExtension` as it no longer handles null values with toOptional.

```
 Optional<T> get toOptional => Optional.of(this);
```
Should be
```
 Optional<T> get toOptional => Optional.ofNullable(this);
```

Missing test case for `test/src/extension.dart`
```
    test('null.toOptional == Optional.empty()', () {
      expect(null.toOptional, equals(Optional.empty()));
    });
```

Many thanks!
James

**Comment by tonio-ramirez** [comment]
`null.toOptional` is an error under Dart's sound null safety.  Support for that construct was removed when support for null safety was introduced.

To be clear, even if the code were reverted to what you suggest, Dart would refuse to run code like `null.toOptional`, with the following error:

> Error: Property 'toOptional' cannot be accessed on 'Null' because it is potentially null.

**Comment by JamesMcIntosh** [comment]
I see what you're saying, this is a more realistic test:
```
test('nullValue.toOptional == Optional.empty()', () {
  final String? nullValue = null;
  expect(nullValue.toOptional, equals(Optional.empty()));
});
```

**Comment by tonio-ramirez** [comment]
The problem isn't the test.  It's that the construct isn't valid.  You can't invoke methods/properties of a reference to a nullable type.  The test you suggest would also fail to run, with the same error.

**Comment by JamesMcIntosh** [comment]
So sad! This makes the extension literally half as useful.
I had a good read of the GitHub discussion around this (https://github.com/dart-lang/language/issues/392 & https://github.com/dart-lang/language/issues/393) and can see why they chose it in regards to shorting and call ambiguity but this is the perfect case where it is needed.
