### ISSUE TITLE
Release 6.0.0 any time soon ?

### ISSUE THREAD

**Issue by hicnar** [tonio-ramirez/optional.dart#17]
Any chances the ^6.0.0-nullsafety.2 will become the 6.0.0 release sooner rather than later?

**Comment by tonio-ramirez** [comment]
6.0.0 release has been waiting for [`test_coverage` ](https://github.com/pulyaevskiy/test-coverage/issues/33), but that doesn't seem to be moving.  I'll remove the dependency and go ahead and release.

**Comment by tonio-ramirez** [comment]
Package published as 6.0.0
