### ISSUE TITLE
Nullable parameter type

### ISSUE THREAD

**Issue by enzo-santos** [tonio-ramirez/optional.dart#20]
Suppose I want an object `o` of type `Optional<String?>`, where

- if `!o.isPresent`, the user ID is being loaded
- if `o.isPresent` and `o.value == null`, the user has not an ID
- if `o.isPresent` and `o.value != null`, the user has an ID of value `o.value`

If I create an `Optional.of(null)`, this would incorrectly raise an ArgumentError. If I create an `Optional.ofNullable(null)`, which is equivalent as creating an `Optional.empty()`, this would incorrectly give an absent-optional when I expected a present-optional containing a null value.

I'm actually wondering if that if-check on `Optional.of` is really necessary after null-safety. If we can't remove it because of backwards-compatibility, should we create a new constructor for this matter?

```dart
factory Optional.present(T value) {
  return _Present<T>(value);
}
```

**Comment by tonio-ramirez** [comment]
Optionals are explicitly used for non-nullable types.  There is not much utility to Optionals when applied to nullable types, and the difference between an empty optional and a present optional containing `null` is tenuous at best.

This package was authored before null safety was introduced to the language, and therefore before explicitly nullable types existed.  I'm tempted to explicitly forbid creating Optionals of nullable types, such that `Optional<String?>.of(aString)` is an error regardless of the value of `aString`.

**Comment by enzo-santos** [comment]
> There is not much utility to Optionals when applied to nullable types

Do you think better `copyWith` methods are a valid argument to make you reconsider?

For example, if I have a class with nullable fields:

```dart
class Foo {
  final String? a;
  final int? b;
  final bool? c;

  const Foo({this.a, this.b, this.c});

  Foo copyWith({String? a, int? b, bool? c}) {
    // Does `a` should be ignored or set to null?
  }
}
```

A possibility here is to use Optionals.

Using Optionals *without* nullable types:

```dart
class Foo {
  final String? a;
  final int? b;
  final bool? c;

  const Foo({this.a, this.b, this.c});

  Foo copyWith({
    Optional<String>? a,
    Optional<int>? b,
    Optional<bool>? c,
  }) {
    return Foo(
      a: a == null ? this.a : a.orElseNull,
      b: b == null ? this.b : b.orElseNull,
      c: c == null ? this.c : c.orElseNull,
    );
  }
}
```

Using Optionals *with* nullable types:

```dart
class Foo {
  final String? a;
  final int? b;
  final bool? c;

  const Foo({this.a, this.b, this.c});

  Foo copyWith({
    Optional<String?> a = const Optional.empty(),
    Optional<int?> b = const Optional.empty(),
    Optional<bool?> c = const Optional.empty(),
  }) {
    return Foo(
      a: a.orElse(this.a),
      b: b.orElse(this.b),
      c: c.orElse(this.c),
    );
  }
}
```

This use case is the main reason I've created this issue, since I believe there is no Dart built-in type to simulate this. But if you still think this use case is not enough to introduce a new constructor to `Optional`, you can close this issue, not a big problem :sweat_smile:

**Comment by tonio-ramirez** [comment]
The entire point of Optionals is to allow a developer to represent a field that may or may not have a value, without having to use `null`s.  In your example above, Foo.a, Foo.b, and Foo.c are all nullable, and might be better described by using Optionals rather than nullable types.

In other words, while you certainly _can_ use both nullable types and Optionals in your code, Optionals are meant to _replace_ nullable types.
